---
- hosts: localhost
  sudo: true
  remote_user: douglas
  vars:
    default_database_root_password: "fargo"
    database_username: douglas
    database_password: fargo
    project: SARAH
    ip_address: "192.168.2.{% if environment_tier=='development' %}91{% elif environment_tier=='production' %}11{% endif %}"
    dryrun: "{% if environment_tier == 'development' %}no{% else %}yes{% endif %}"
  roles:
    - role: stevenharradine.static-ip
      static_ip_address: "{{ ip_address }}"
      static_ip_dryrun: dryrun | bool
    - role: stevenharradine.hostname
      hostname_dryrun: dryrun | bool
  tasks:
  - name: install software | apt
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - htop
      - git
      - ruby-sass
      - nodejs
      - npm
      - apache2
      - "php{% if ansible_distribution_major_version <= 14 %}5{% endif %}"
      - mysql-server
      - python-mysqldb
      - "php{% if ansible_distribution_major_version <= 14 %}5{% endif %}-mysql"
      - "libapache2-mod-php{% if ansible_distribution_major_version <= 14 %}5{% endif %}"
      - "php{% if ansible_distribution_major_version <= 14 %}5{% endif %}-curl"

  - name: install software | npm
    npm:
      name: "{{ item }}"
      state: latest
      global: yes
    with_items:
      - grunt
      - grunt-cli

  - name: checkout framework
    git:
      repo: https://github.com/stevenharradine/SARAH-framework.git
      dest: /etc/SARAH/
      version: master
      force: yes

  - name: change framework permissions
    file:
      path: /etc/SARAH
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
      mode: 0755

  - name: add media.conf and sarah.conf to apache2.conf
    lineinfile:
      dest: /etc/apache2/apache2.conf
      insertafter: EOF
      line: "Include /etc/SARAH/apache2/{{ item }}.conf"
    with_items:
      - sarah
      - media
    notify:
      - restart apache

  - name: update php session timeout
    lineinfile:
      dest: "{% if ansible_distribution_major_version <= 14 %}/etc/php5/apache2/php.ini{% else %}/etc/php/7.0/apache2/php.ini{% endif %}"
      regexp: ^session.gc_maxlifetime
      line: session.gc_maxlifetime = 172800
    notify:
      - restart apache

  - name: redirect docroot to /SARAH
    lineinfile:
      dest: /var/www/html/index.html
      insertafter: EOF
      line: "<script>location.href='/SARAH'</script>"

  - name: restart apache
    service:
      name: apache2
      state: restarted

  - name: set root password
    mysql_user:
      login_user: root
      login_password: ""
      name: root
      password: "{{ default_database_root_password }}"
    ignore_errors: yes

  - name: create sarah user account
    mysql_user:
      login_user: root
      login_password: "{{ default_database_root_password }}"
      name: "{{ database_username }}"
      password: "{{ database_password }}"
      priv: "*.*:ALL,GRANT"

  - name: symlink node
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      owner: www-data
      group: www-data
      state: link

  - name: install npm via package.json
    sudo_user: root
    npm:
      path: /etc/SARAH

  - name: update apps
    sudo_user: root
    shell: node /etc/SARAH/scripts/setup-apps.js > /etc/SARAH/scripts/setup-apps.log
    tags:
      - deploy

  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted
