- hosts: globaldynamics
  vars:
    http_port: 80
    max_clients: 200
  sudo: true
  remote_user: douglas

  tasks:
  - name: install software
    apt:
      pkg: "{{ item }}"
      state: latest
    with_items:
      - apache2
      - php5
      - mysql-server
      - python-mysqldb
      - php5-mysql
      - libapache2-mod-php5


#  - name: write the apache config file
#    template:
#      src: /srv/httpd.j2
#      dest: /etc/httpd.conf
#    notify:
#    - restart apache

#  - name: ensure apache is running (and enable it at boot)
#    service:
#      name: httpd
#      state: started
#      enabled: yes

#  handlers:
#  - name: restart apache
#    service:
#      name: httpd
#      state: restarted
