---
- hosts: SARAH
  sudo: true
  remote_user: douglas
  vars:
    default_database_root_password: "fargo"
    database_username: douglas
    database_password: fargo
  tasks:
  - name: install software | apt
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - htop
      - git
      - ruby-sass
      - nodejs
      - npm
      - apache2
      - php5
      - php5-mcrypt
      - mysql-server
      - python-mysqldb
      - php5-mysql
      - libapache2-mod-php5
      - openjdk-7-jdk
      - libav-tools
      - php5-curl

  - name: enable mcrypt
    command: php5enmod mcrypt

  - name: install software | npm
    npm:
      name: "{{ item }}"
      state: latest
      global: yes
    with_items:
      - grunt
      - grunt-cli

  - name: checkout framework
    git:
      repo: https://github.com/stevenharradine/SARAH-framework.git
      dest: /etc/SARAH/
      version: master
      force: yes

  - name: change framework permissions
    file:
      path: /etc/SARAH
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
      mode: 0755

  - name: add media.conf and sarah.conf to apache2.conf
    lineinfile:
      dest: /etc/apache2/apache2.conf
      insertafter: EOF
      line: "Include /etc/SARAH/apache2/{{ item }}.conf"
    with_items:
      - sarah
      - media
    notify:
      - restart apache

  - name: restart apache
    service:
      name: apache2
      state: restarted

  - name: set root password
    mysql_user:
      login_user: root
      login_password: ""
      name: root
      password: "{{ default_database_root_password }}"
    ignore_errors: yes

  - name: create sarah user account
    mysql_user:
      login_user: root
      login_password: "{{ default_database_root_password }}"
      name: "{{ database_username }}"
      password: "{{ database_password }}"
      priv: "*.*:ALL,GRANT"

  - name: symlink node
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      owner: www-data
      group: www-data
      state: link

  - name: install npm via package.json
    sudo_user: root
    npm:
      path: /etc/SARAH

  - name: update apps
    sudo_user: root
    command: node /etc/SARAH/scripts/setup-apps.js
    tags:
      - deploy

  - name: reader | cron
    sudo_user: www-data
    cron:
      name: "Reader updater"
      special_time: reboot
      job: "cd /etc/SARAH/www/apps/SARAH-reader/updater/ &&  bash run.sh"

  # - name: reader | cron
  #   sudo_user: www-data
  #   cron:
  #     name: "Reader updater"
  #     special_time: reboot
  #     job: "cd /etc/SARAH/www/apps/SARAH-reader/updater/ &&  bash run.sh"
  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted
